server:
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
       content-type: text/html
    mode: HTML5
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.189.128:3306/bigfile?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    abandon-when-percentage-full: 70
    connection-test-query: '"SELECT 1"'
    initialSize: 3
    log-abandoned: true
    max-active: 40
    max-idle: 40
    maximum-pool-size: 40
    min-idle: 3
    numTestsPerEvictionRun: 40
    remove-abandoned: true
    remove-abandoned-timeout: 180
    test-on-borrow: true
    test-while-idle: true
    timeBetweenEvictionRunsMillis: 60000
    validation-query: SELECT 1


epb:
  bigfile:
    split-file-path: D:\test\bigfile
    domain-lob-site-path: D:\test\domain_lob_site.xlsx
    site-file-path: D:\test\sitefile
    bak-file-path: D:\test\bak\
    uploader-username: 66776677
    uploader-password: 123456
    max-upload-attempt-number: 3
  kafka:
    producer:
      servers: localhost:9092

logging:
#  level:
#    com.symbio.epb.bigfile.mapper: DEBUG
  path: /var/logs/bigfile