server:
  port: 8085
  connectionTimeout: 240000
  

   
spring:
  http:
    multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  datasource:
    url: jdbc:mysql://rds-staging-01.ppro360.com:3306/bigfile?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: normal
    password: A3EDD019E341B5A124986FEAF78F20C7
    abandon-when-percentage-full: 70
    connection-test-query: '"SELECT 1"'
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 3
    log-abandoned: true
    max-active: 40
    max-idle: 40
    maximum-pool-size: 40
    min-idle: 3
    numTestsPerEvictionRun: 40
    remove-abandoned: true
    remove-abandoned-timeout: 180
    test-on-borrow: true
    test-while-idle: true
    timeBetweenEvictionRunsMillis: 60000
    validation-query: SELECT 1
  mvc:
    async:
      request-timeout: 240000


epb:
  bigfile:
    split-file-path: /opt/bigfile/split
    domain-lob-site-path: /opt/bigfile/domain_lob_site.xlsx
    site-file-path: /opt/bigfile/splitSite
    bak-file-path: /opt/bigfile/bak/
    uploader-username: 66776677
    uploader-password: 123456
    max-upload-attempt-number: 3
  kafka:
    producer:
      servers: 34.212.127.229:9092

logging:
  path: /var/logs/bigfile